### ISSUE TITLE
bubble

### ISSUE THREAD

**Issue by iFuhang** [iFuhang/Notes#1]
实现类似购物车图标上面的数量提示，当数量为1位数字时显示圆圈，超出1位数字时显示类似椭圆的形状(不知道该怎么描述了(^~^)。

```html
  <div class="bubble">1</div>
  <div class="bubble">12</div>
```

```css
  .bubble {
    display: inline-block;
    min-width: 12px;
    padding: 3px;
    line-height: 6px;
    border: 1px solid #333;
    border-radius: 99px;
    box-sizing: border-box;
    font-size: 12px;
  }
```
